sudo: required

services:
  - docker

before_install:
  - cd client && docker build -t moumenh/client .
  - cd backend && docker build -t moumenh/backend .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push moumenh/client
  - docker push moumenh/backend

