version: "3.9"
   
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  project:
    restart: always
    container_name: code
    command : bash -c "python check_db.py --service-name db --ip db --port 3306 && 
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    volumes:
      - .:/Backend/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
      
  frontend:
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - project

    