version: "3.9"
   
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    restart: on-failure
    container_name: backend
    command : bash -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
  frontend:
    restart: on-failure
    # command : npm start
    container_name: front
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes: 
      - static_volume:/app/backend/static
    ports:
      - "80:80"
    stdin_open: true
    depends_on:
      - backend

volumes: 
  static_volume:

    