# Generated by Django 3.1.4 on 2021-01-15 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.CharField(default='desc', max_length=5000),
        ),
        migrations.AddField(
            model_name='project',
            name='git',
            field=models.CharField(default='link', max_length=1000),
        ),
        migrations.AddField(
            model_name='technologies',
            name='icon',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(default='image', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(default='link', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='title', max_length=250),
        ),
    ]
